# Generated by Django 2.2.10 on 2020-02-28 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=11)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('asking_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('buying_price', models.IntegerField()),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Catagory')),
                ('p_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('p_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Products')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='rack_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Rack'),
        ),
    ]
